scsi: ufs: Fix unused function when tracepoints are disabled
This silences the following compiler warning:

../drivers/scsi/ufs/ufshcd.c:686:13: error: unused function
'__ufshcd_cmd_log' [-Werror,-Wunused-function]
static void __ufshcd_cmd_log(struct ufs_hba *hba, char *str, char *cmd_type,
            ^

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>
Signed-off-by: Julian Liu <wlootlxt123@gmail.com>
Signed-off-by: Yousef Algadri <yusufgadrie@gmail.com>
Signed-off-by: sohamxda7 <sensoham135@gmail.com>
Signed-off-by: ImSpiDy <SpiDy2713@gmail.com>